version: 2.1

orbs:
  yell: jaysonesmith/demo@dev:0.1.0

jobs:
  orb-use-example:
    docker:
      - image: cimg/base:stable
    steps:
      - yell/yell:
          person: Jayson

workflows:
  test_my_app:
    jobs:
      - orb-use-example
