version: 2.1

jobs:
  install-node-example:
    executor: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version

orbs:
  node: circleci/node@10.18.1-stretch

workflows:
  test_my_app:
    jobs:
      - install-node-example
